# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 984e0f3f15a95dfeb407bad6b6af60cbc6c2fc2be8c8a93c25ac3156d2bf3463a8247a2ab8cc4cea1e470902e87602079a4cdcc12a899574447311930123b648

test:
  secret_key_base: 5f6ea6ff0b7b0fdfb22112bc53f1d0f5d22397d7e43c7059648bd757d27a9d08d4df09d48ed37666d9f8790631c5810098cd172c80c76caaf620785f04e49bc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
